### ISSUE TITLE
Create a github template

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#21]
- Background
- Acceptance Criteria

**Comment by colinmurphy01** [comment]
Let's test [this feature](https://gsa-tts.slack.com/archives/C22CC7RD5/p1681927776906899) once we create a template

**Comment by colinmurphy01** [comment]
@cannandev I'll take over this since I'm taking responsibility for our workflow stuff in github.

**Comment by mgwalker** [comment]
The linked feature is typing `/template` in an empty issue or pull request to pull the template into it. That can be useful especially useful when creating an issue directly from the board, since by default that way doesn't use the template.

There are other [slash commands you can use in GitHub Markdown](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-slash-commands) as well.

**Comment by colinmurphy01** [comment]
updated issue templates, however still figuring out how to track work between epics and sprints
