### ISSUE TITLE
CMS Options and Decision

### ISSUE THREAD

**Issue by colinmurphy01** [18F/weather.gov#66]
### Description

**Outcome: a sustainable and compliant architecture**

### Justification
- Value: High
- Viability: Medium
- Alignment: High

```[tasklist]
### Rocks
- [ ] #20 
- [ ] #7 
- [ ] #19 
- [ ] #120 
- [ ] #121 
- [ ] #132 
```

**Comment by mgwalker** [comment]
@cannandev I propose an interim ADR where we choose to use a site-builder CMS rather than a headless CMS. That seems like a separate decision from which CMS to use to me, and I think you and I are in agreement about it. What do you think? I'm happy to write up the draft ADR if you think that makes sense.

**Comment by colinmurphy01** [comment]
With the ADR's written #186 #187 #163 and in review I believe we can close this ticket.
